### ISSUE TITLE
使用github action自動執行colab notebook

### ISSUE THREAD

**Issue by kevin930321** [chikenscrach/myba#1]
如題，不知道有沒有辦法

**Comment by chikenscrach** [comment]
或許有辦法，不過之前@JacobLinCool做的就被鎖了，你可以研究一下我的workflow和merge.js

**Comment by kevin930321** [comment]
我上網查好像是模組路徑要改成import /home/runner/work/repo/repo/模組名/index.js 但我找不到哪裡可以改路徑

**Comment by chikenscrach** [comment]
這樣的話我還是建議問一下原作者，畢竟這個程式並不是我打，我也希望開issue是為了ipynb裡有bug作回報
